//REQUISICOES PARA RECEITAS
GET http://localhost:4002/products

###

GET http://localhost:4002/products/14

###

GET http://localhost:4002/products/Anis

//----------------------------------------------------------------------------
//REQUISICOES PARA RECEITAS

###
//Retorna todos as receitas
GET http://localhost:4002/recipes

###
GET http://localhost:4002/recipes/ingredients?ingredients=chocolate,farinha de trigo,


