//REQUISICOES PARA RECEITAS
GET http://localhost:4002/products

###

GET http://localhost:4002/products/143

###

GET http://localhost:4002/products/Acerola

//----------------------------------------------------------------------------
//REQUISICOES PARA RECEITAS

###
//Retorna todos as receitas
GET http://localhost:4001/recipes

###

GET http://localhost:4001/recipes/name/Bolo de Chocolate

###

GET http://localhost:4001/recipes/hard